session14/session14/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'

urlpatterns = [
    # /accounts/
    path('', views.home, name = 'home'),
]

session14/session14/app14/urls.py
from django.urls import path
from app14 import views

app_name = 'app14'
# 중복을 피하기 위한 url 네임스페이스
urlpatterns = [
    # /app14/
    path('', views.home, name = 'home'),
    path('new/', views.new, name="new"),
    path('detail/<int:post_pk>/', views.detail, name="detail"),
    path('edit/<int:post_pk>/', views.edit, name="edit"),
    path('delete/<int:post_pk>/', views.delete, name="delete"),
]

session14/session14/session14/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app14/', include('app14.urls')),
    path('accounts/', include('accounts.urls')),
    # blog/로 시작되는 url이면, blog하위에 있는 url을 불러온다. 
]

session14/session14/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

session14/session14/app14/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Post(models.Model):
# 모델 속성 : 데이터베이스 테이블의 컬럼 = 모델 클래스의 속성 = 모델 클래스의 필드 (ORM)
    title = models.CharField(verbose_name='TITLE', max_length=50)
    # CharField는 max_length가 필수. form에서 input tag
    content = models.TextField()
    # TextField는 form에서 textarea tag
    create_dt = models.DateTimeField(auto_now_add=True)
    # auto_now_add는 생성 시각 기준으로 자동 생성
    update_dt = models.DateTimeField(auto_now=True)
    # auto_now는 저장 시각 기준으로 자동 생성
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_posts")
    # ForignKey는 1:N에서 N에서 설정. CASCADE가 있는 속성에 해당하는 데이터 삭제 시, 그를 포함하는 모든 객체 삭제. related_name은 역참조할 때 사용

# 메타 데이터 : 데이터에 대한 데이터. Meta 내부 클래스를 정의해 사용
    class Meta: 
        verbose_name = 'post' 
        # 모델 객체의 별칭. 
        verbose_name_plural = 'posts'
        # 별칭의 복수형 명칭
        ordering = ('-create_dt', 'author')
        # 모델 객체 리스트 출력시 정렬 기준. -면 내림차순. 위의 경우에는 create_dt 기준으로 내림차순 후 author 기준으로 오름차순. 
# 모델 메소드 : 클래스 메소드가 아니라 객체 메소드. 항상 self인자를 가지고 있으며, 테이블 단위가 아니라 레코드 단위에 영향을 미친다. (테이블 단위는 views에서 Post.objects.all() 등으로 사용)
    def __str__(self):
        # 자신(객체)의 문자열 표현을 반환한다. 
        # return self.title
        return f'{self.title}입니다.'

    def get_absolute_url(self):
        # 자신(객체)의 url을 반환한다. detail을 보여주는 경우 위 메소드를 사용하면 편하다. 
        return reverse(f'blog:post_detail', args=[self.id])

    # create_dt기준으로 앞 뒤 객체 반환.
    def get_previous(self):
        return self.get_previous_by_create_dt()

    def get_next(self):
        return self.get_next_by_create_dt()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_comments")
    content = models.TextField()
    create_dt = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-create_dt', 'post', 'author')

    def __str__(self):
        return f'{self.author}-{self.content}'

session14/session14/accounts/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'accounts/home.html')

session14/session14/app14/views.py
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.
def home(request):
    posts = Post.objects.all()

    return render(request, 'app14/home.html', {'posts':posts})

def new(request):
    if request.method == "POST":
        new_post = Post.objects.create(
            title = request.POST['title'],
            content = request.POST['content']
        )
        return redirect('detail', new_post.pk)

    return render(request, 'app14/new.html')

def detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)

    return render(request, 'app14/detail.html', {'post':post})

def edit(request, post_pk):
    post = Post.objects.get(pk=post_pk)

    if request.method == 'POST':
        Post.objects.filter(pk=post_pk).update(
            title = request.POST['title'],
            content = request.POST['content']
        )
        return redirect('detail', post_pk)

    return render(request, 'app14/edit.html', {'post':post})

def delete(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    post.delete()

    return redirect('home')

session14/session14/accounts/templates/accounts/home.html
<div>
    <h1>독후감 블로그-회원관리</h1>
    <a href="{% url 'app14:home' %}">독후감 블로그</a>
</div>

session14/session14/app14/templates/app14/detail.html
<body>
    <div>
        <h2>제목</h2>
        <p>{{ post.title }}</p>
    </div>
    <div>
        <h2>내용</h2>
        <p>{{ post.content }}</p>
    </div>
    <a href="{% url 'app14:home' %}">홈으로</a>
    <a href="{% url 'app14:edit' post.pk %}">수정하기</a>
    <a href="{% url 'app14:delete' post.pk %}">삭제하기</a>
</body>

session14/session14/app14/templates/app14/edit.html
<body>
    <form action="" method="post">
        {% csrf_token %}
        <div>
            <label for="title">제목</label>
            <input type="text" id="title" name="title" value="{{ post.title }}">
        </div>
        <div>
            <label for="content">내용</label>
            <textarea name="content" id="content" cols="30" rows="10">{{ post.content }}</textarea>
        </div>
        <button type="submit">수정하기</button>
    </form>
</body>

session14/session14/app14/templates/app14/home.html
<body>
    <h1>독후감 블로그</h1>
    <div>
        <ul>
            {% for post in posts %}
            <li>
                <a href="{% url 'app14:detail' post.pk %}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <a href="{% url 'app14:new' %}">글 쓰러가기</a>
</body>

session14/session14/app14/templates/app14/new.html
<body>
    <form action="" method="post">
        {% csrf_token %}
        <div>
            <label for="title">제목</label>
            <input type="text" id="title" name="title" placeholder="제목을 입력해주세요.">
        </div>
        <div>
            <label for="content">내용</label>
            <textarea name="content" id="content" cols="30" rows="10" placeholder="내용을 입력해주세요."></textarea>
        </div>
        <button type="submit">작성하기</button>
    </form>
</body>